name: Manual Hotel Rate Check
on:
  workflow_dispatch:
    inputs:
      check_in:
        description: 'Check-in date (YYYY-MM-DD)'
        required: true
        default: '2025-06-01'
      check_out:
        description: 'Check-out date (YYYY-MM-DD)'
        required: true
        default: '2025-06-02'

jobs:
  scrape-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install
          npx playwright install chromium
          
      - name: Run rate scraper
        env:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          CHECK_IN: ${{ github.event.inputs.check_in }}
          CHECK_OUT: ${{ github.event.inputs.check_out }}
        run: node scraper.js
        
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: rate-results
          path: results.json
